Laboratory56/Laboratory56/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Laboratory56.Data;
using Laboratory56.Models;
using Laboratory56.Models.AccountViewModels;
using Laboratory56.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace Laboratory56.Controllers
{
    public class ApplicationUsersController : Controller
    {
        #region Conect and ctor

        public ApplicationUsersController(
            ApplicationDbContext context, 
            IHostingEnvironment environment, 
            FileUploadService fileUploadService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _environment = environment;
            _fileUploadService = fileUploadService;
            _userManager = userManager;
        }
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;
        

        #endregion

        #region AllUser

        public ActionResult UsersList()
        {
            return View(_context.Users.ToList());
        }

        #endregion

        #region Index

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApplicationUser.ToListAsync());
        }

        #endregion

        #region Details

        // GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser
                .SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }
        


        #endregion

        #region Create

        // GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,AvatarImage,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }
        

        #endregion

        #region Edit

        // GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,AvatarImage,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser, ApplicationUserVM model)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }
            var applicationUserList = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (ModelState.IsValid)
            {
                try
                {
                    var path = Path.Combine(
                        _environment.WebRootPath,
                        $"images\\{_userManager.GetUserName(User)}\\avatar");
                    _fileUploadService.Upload(path, model.AvatarImage.FileName, model.AvatarImage);
                    var avatarImageVar = $"images/{_userManager.GetUserName(User)}/avatar/{model.AvatarImage.FileName}";

                    applicationUserList.AvatarImage = avatarImageVar;
                    applicationUserList.UserName = applicationUser.UserName;
                    applicationUserList.Email = applicationUser.Email;
                    applicationUserList.PhoneNumber = applicationUser.PhoneNumber;


                    _context.Update(applicationUserList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }
        

        #endregion

        #region Delete

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser
                .SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }

        #endregion
    }
}

Laboratory56/Laboratory56/Controllers/PublicationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Laboratory56.Data;
using Laboratory56.Models;
using Laboratory56.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace Laboratory56.Controllers
{
    public class PublicationsController : Controller
    {
        #region Conections and Constructor

        public PublicationsController(ApplicationDbContext context, IHostingEnvironment environment,
            FileUploadService fileUploadService, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _environment = environment;
            _fileUploadService = fileUploadService;
            _userManager = userManager;
        }

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;

        #endregion

        #region Index

        // GET: Publications
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                var sort = await _context.Publications
                    .Include(s => s.User)
                    .Where(p => p.UserId == user.Id)
                    .OrderByDescending(s => s.Id)
                    .ToListAsync();

                return View(sort);
            }
            else
            {
                var sort = await _context.Publications
                    .Include(s => s.User)
                    .OrderByDescending(s => s.Id)
                    .ToListAsync();

                return View(sort);
            }
        }

        #endregion

        #region Details

        // GET: Publications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publication = await _context.Publications
                .SingleOrDefaultAsync(m => m.Id == id);
            if (publication == null)
            {
                return NotFound();
            }

            return View(publication);
        }

        #endregion

        #region Create

        // GET: Publications/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImadeUrl,Description,Like,RePost")]
            Publication publication, PublicationVM model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var pub = Publication(publication, model);
                pub.UserId = user.Id;
                _context.Add(pub);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(publication);
        }

        #endregion

        #region Edit

        // GET: Publications/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publication = await _context.Publications.SingleOrDefaultAsync(m => m.Id == id);
            if (publication == null)
            {
                return NotFound();
            }

            return View(publication);
        }

        // POST: Publications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImadeUrl,Description,Like,RePost")]
            Publication publication, PublicationVM model)
        {
            if (id != publication.Id)
            {
                return NotFound();
            }

            var searching = await _context.Publications.SingleOrDefaultAsync(s => s.Id == id);

            if (ModelState.IsValid)
            {
                try
                {
                    var path = Path.Combine(_environment.WebRootPath,
                        $"images\\{_userManager.GetUserName(User)}\\Publication");

                    _fileUploadService.Upload(path, model.ImageUrl.FileName, model.ImageUrl);
                    var imageUrlContent =
                        $"images/{_userManager.GetUserName(User)}/Publication/{model.ImageUrl.FileName}";

                    searching.Description = publication.Description;
                    searching.ImageUrl = imageUrlContent;

                    _context.Update(searching);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublicationExists(publication.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(publication);
        }

        #endregion

        #region PublicationUpload

        private Publication Publication(Publication publication, PublicationVM model)
        {
            var path = Path.Combine(_environment.WebRootPath, $"images\\{_userManager.GetUserName(User)}\\Publication");

            _fileUploadService.Upload(path, model.ImageUrl.FileName, model.ImageUrl);
            var imageUrlContent = $"images/{_userManager.GetUserName(User)}/Publication/{model.ImageUrl.FileName}";

            var pub = new Publication
            {
                ImageUrl = imageUrlContent,
                Description = publication.Description
            };
            return pub;
        }

//        // для тестов
//        private Publication PublicationEdit(Publication publication, PublicationVM model)
//        {
//            var path = Path.Combine(_environment.WebRootPath, $"images\\{_userManager.GetUserName(User)}\\Publication");
//
//            _fileUploadService.Upload(path, model.ImageUrl.FileName, model.ImageUrl);
//            var imageUrlContent = $"images/{_userManager.GetUserName(User)}/Publication/{model.ImageUrl.FileName}";
//
//            var pub = new Publication
//            {
//                ImageUrl = imageUrlContent,
//                Description = publication.Description
//            };
//            return pub;
//        }

        #endregion

        #region Delete

        // GET: Publications/Delete/5
        // [AllowAnonymous]
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publication = await _context.Publications
                .SingleOrDefaultAsync(m => m.Id == id);
            if (publication == null)
            {
                return NotFound();
            }

            return View(publication);
        }

        // POST: Publications/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publication = await _context.Publications.SingleOrDefaultAsync(m => m.Id == id);
            _context.Publications.Remove(publication);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublicationExists(int id)
        {
            return _context.Publications.Any(e => e.Id == id);
        }

        #endregion

        #region LikeMethod

        public ActionResult LikeMethod(string userId, int postId)
        {
            var userLike = _context.Publications.FirstOrDefault(u => u.Id == postId);
            if (ModelState.IsValid)
            {
                if (userLike != null)
                {
                    userLike.Like = userLike.Like + 1;

                    _context.Update(userLike);
                    _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            return View();
        }

        #endregion

        #region DisLikeMethod

        public ActionResult DisLikeMethod(string userId, int postId)
        {
            var userLike = _context.Publications.FirstOrDefault(u => u.Id == postId);
            if (ModelState.IsValid)
            {
                if (userLike != null)
                {
                    userLike.Like = userLike.Like - 1;


                    _context.Update(userLike);
                    _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            return View();
        }

        #endregion

        #region SubscriptionMethod

        public ActionResult SubscriptionMethod(string userId, int postId)
        {
            var userLike = _context.Publications.FirstOrDefault(u => u.Id == postId);
            if (ModelState.IsValid)
            {
                if (userLike != null)
                {

Laboratory56/Laboratory56/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Laboratory56/Laboratory56/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Laboratory56/Laboratory56/Views/Home/Index.cshtml
@model IEnumerable<Laboratory56.Models.Publication>
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>
<a asp-area="" asp-controller="Publications" asp-action="Create"><h4>Создать пост</h4></a>

@foreach (var item in Model)
{
   
    @Html.Partial("_PartialView", item)

}



@*
@section Scripts{
    <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover({
                title: setData,
                html: true,
                placement: 'right'
            });

            function setData(id) {
                var set_data = '';
                var element = $(this);
                var id = element.attr("id");
                $.ajax({
                    url: "/Home/UsersInfo?id" + id,
                    method: "post",
                    async: false,
                    data: { id: id },
                    success: function (data) {
                        set_data = data;
                    }
                });
                return set_data;
            }
        });
    </script>
}
*@

Laboratory56/Laboratory56/Views/Home/Searching.cshtml
@{
    ViewData["Title"] = "Searching";
}

<h2>Searching</h2>

<div class="row">
    <div class="col-lg-pull-4">
        <input type="text" name="searchingKey" id="search"/>
        <input type="button" id="submit" value="Наити"/>
        <div class="col-lg-8" id="result"></div>
    </div>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function() {
            $('#submit').click(function(e) {
                e.preventDefault();
                var str = $('#search').val();
                str = encodeURIComponent(str);
                $('#result').load('@Url.Action("SearchingResult", "Home")?key=' + str);
            });
        });
    </script>
}

Laboratory56/Laboratory56/Views/Home/UserSearchResult.cshtml
@model IEnumerable<Laboratory56.Controllers.HomeController.UserListElements>

@{
    ViewData["Title"] = "Index";
}

<h2>Анкета пользователя</h2>

<table class="table" width="350">
    <thead>
        <tr>

            <th>
                Аватар
            </th>
            @* <th> *@
            @*     Id *@
            @* </th> *@
            <th>
                Имя
            </th>
            <th>
                E-mail
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/@item.AvatarImages" width="350" height="250" />
                </td>
                @* *@
                @* <td> *@
                @*     @Html.DisplayFor(modelItem => item.Id) *@
                @* </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Laboratory56/Laboratory56/Views/Home/UsersInfo.cshtml
@model IEnumerable<Laboratory56.Models.ApplicationUser>

@{
    ViewBag.Title = "UsersInfo";
}

<div class="container">
    @foreach (var item in Model)
    {
        <p ><img src="~/@item.AvatarImage" width="100" height="100"/></p><br/>
        <p style="color: black;"><label style="color: darkgrey;"> Name: </label>@item.Name</p>
        <p style="color: dodgerblue;"><label style="color: darkgrey;"> Email: </label>@item.Email</p>
        <p style="color: dodgerblue;"><label style="color: darkgrey;"> PhoneNumber: </label>@item.PhoneNumber</p>
    }
</div>

Laboratory56/Laboratory56/Views/Home/UsersList.cshtml
@model IEnumerable<Laboratory56.Models.ApplicationUser>


<div class="container">
    <h3 style="text-align: inherit">Все пользователи</h3><br/>
    
    <table class="table table-bordered">
        <tr>
            <th style="width: 10%">ID</th>
            <th style="width: 90%">Name</th>
        </tr>
        
        @foreach (var item in Model)
        {
            <tr>
                @* <td><img src="~/@item.AvatarImage" width="100" height="100" /></td> *@
                <td><img src="~/@item.AvatarImage" width="100" height="100" /></td>
                <td ><a 
                         asp-controller="ApplicationUsers" 
                         asp-action="UsersList" 
                         data-toggle="popover" 
                         data-trigger="hover" 
                         id="@item.Id">@item.Name</a></td>
            </tr>
          
        }
    </table>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function() {
            $('[data-toggle="popover"]').popover({
                title: setData,
                html: true,
                placement: 'right'
            });

            function setData(id) {
                var set_data = '';
                var element = $(this);
                var id = element.attr("id");
                $.ajax({
                    url: "/Home/UsersInfo?id" + id,
                    method: "post",
                    async: false,
                    data: { id: id },
                    success: function(data) {
                        set_data = data;
                    }
                });
                return set_data;
            }
        });
    </script>
}